image: php:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: laravel_app
  MYSQL_ROOT_PASSWORD: secret

cache:
  paths:
    - vendor/

test:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
  before_script:
    - apt-get update -yqq
    - apt-get install gnupg -yqq
    - apt-get install git zip unzip libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - docker-php-ext-install pdo pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate
    - php artisan db:seed
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
